import LocalizedStrings from 'react-native-localization';

export const lang = new LocalizedStrings({
  en: {
    /// Setup section
    setup_title: 'Set up WoWs Info',
    setup_done_button: 'Done',
    setup_loading: 'Loading...',
    /// Home section
    // Friend section
    friend_clan_title: 'Clan',
    friend_player_title: 'Player',
    // Update section
    update_version_title: 'Version',
    update_app_version: 'App →',
    update_game_version: 'Game →',
    // Button section
    button_settings_label: 'Settings',
    button_menu_label: 'Menu',
    button_back_label: 'Go Back',
    button_home_label: 'Home',
    /// Wiki section
    wiki_warship_footer: 'Filter',
    wiki_warship_filter_btn: 'Apply Filters',
    wiki_warship_reset_btn: 'Reset',
    wiki_warship_filter_placeholder: 'Enter a Ship Name',
    wiki_warship_filter_tier: 'Tier',
    wiki_warship_filter_nation: 'Nation / Region',
    wiki_warship_filter_type: 'Type',
    wiki_warship_filter_premium: 'Premium Ship',
    // Warship Detail
    warship_unknown: 'Unknown',
    warship_model: '3D Model',
    warship_update_module: 'Update Ship Modules',
    warship_default_module: 'Default',
    warship_apply_module: 'Apply Modules',
    warship_survivability: 'Survivability',
    warship_survivability_health: 'Health',
    warship_survivability_armour: 'Armour',
    warship_survivability_protection: 'Protection',
    warship_artillery: 'Artillery',
    warship_artillery_main: 'Main Battery',
    warship_avg_damage: 'Average Damage',
    warship_avg_winrate: 'Average Winrate',
    warship_avg_frag: 'Average Frags',
    warship_weapon_reload: 'Reload Time',
    warship_weapon_range: 'Range',
    warship_weapon_configuration: 'Configuration',
    warship_weapon_dispersion: 'Max Dispersion',
    warship_weapon_rotation: 'Rotation Time',
    warship_weapon_fire_chance: 'Fire Chance',
    warship_artillery_main_weight: 'Weight',
    warship_weapon_damage: 'Max Damage',
    warship_weapon_potential_damage: 'Potential Damage',
    warship_weapon_ap_overmatch: 'Overmatch',
    warship_weapon_he_penetration: 'Penetration',
    warship_weapon_speed: 'Speed',
    warship_ramming: 'Ramming',
    warship_artillery_secondary: 'Secondary',
    warship_torpedoes: 'Torpedoes',
    warship_torpedoes_visible_distance: 'Detection',
    warship_antiaircraft: 'AA Defense',
    warship_maneuverability: 'Maneuverability',
    warship_maneuverability_turning: 'Turning Radius',
    warship_maneuverability_speed: 'Max Speed',
    warship_maneuverability_rudder_time: 'Rudder Time',
    warship_aircraft: 'Aircraft',
    warship_concealment: 'Concealment',
    warship_concealment_detect_by_ship: 'Detection by Ship',
    warship_concealment_detect_by_plane: 'Detection by Plane',
    warship_upgrades: 'Upgrades',
    warship_next_ship: 'Next Ship(s)',
    warship_compare_similar: 'Compare Similar Ships',
    /// Menu section
    /// Settings section
    server_name: ['Russia', 'Europe', 'North America', 'Asia'],
    setting_game_server: 'Game Server',
    setting_api_language: 'API Language',
    setting_api_update_data: 'Update data from server',
    setting_api_update_data_title: 'Please only use this when data is missing',
    setting_api_update_data_update: 'Update',
    setting_api_update_data_cancel: 'Cancel',
    setting_app_language: 'WoWs Info Language',
    settings_api_settings: 'API Settings',
    settings_app_settings: 'App Settings',
    settings_app_dark_mode: 'Dark Mode',
    settings_app_theme_colour: 'Theme Colour',
    settings_app_no_image_mode: 'No Image Mode',
    settings_app_swap_buttons: 'Swap Bottom Buttons',
    settings_app_send_feedback: 'Send Feedback',
    settings_app_send_feedback_subtitle: 'Send an Email to the developer',
    settings_app_report_issues: 'Report an Issue',
    settings_app_write_review: 'Write a Review',
    settings_app_write_review_title: 'About Review and Feedback',
    settings_app_write_review_message:
      'If you have any questions, issues, or suggestions, please send an email to the developer so that we can discuss and solve the problem together.',
    settings_app_write_review_yes: 'Send an Email',
    settings_app_write_review_no: 'Write a Review',
    settings_app_share: 'Share with Friends',
    settings_app_share_subtitle: 'Share WoWs Info if you enjoy using it!',
    settings_app_check_for_update: 'Check for Update',
    settings_app_no_update: 'You are using the latest version.',
    settings_app_has_update: 'Update {0} is available',
    settings_open_source: 'Open Source',
    settings_open_source_github: 'GitHub',
    settings_open_source_licence: 'Licences',
    settings_open_source_licence_subtitle:
      'Great modules that are used by WoWs Info',
    // Footer
    menu_footer: 'Search',
    menu_search_player: 'Player',
    menu_search_clan: 'Clan',
    // Pro version
    pro_upgrade_button: 'Upgrade to Pro',
    pro_title: 'WoWs Info Pro',
    pro_rs: 'RS Beta',
    pro_rs_subtitle: 'Get realtime statistics in your battles',
    pro_more_stats: 'More Detailed Statistics',
    pro_more_stats_subtitle: 'Show even more statistics in your profile',
    pro_quick_access_main: 'Quick Access to Main Account',
    pro_quick_access_main_subtitle:
      'Check statistics for your main account with just a tap',
    pro_support_development: 'Support Development',
    pro_support_development_subtitle:
      'More features are currently under development',
    pro_50_off_until_re: '50% Off for the First Purchase',
    pro_per_year: 'Year',
    pro_restore_pro: 'Restore Pro Version',
    iap_thx_for_support: 'Thank you for your support!',
    iap_no_purchase_history: 'No Payment History Found',
    iap_pro_expired: 'WoWs Info Pro has expired',
    // Search bar
    search_player_online: 'Online',
    // Wiki
    wiki_section_title: 'Encyclopedia',
    wiki_achievement: 'Achievement',
    wiki_warships: 'Warships',
    wiki_upgrades: 'Upgrades',
    wiki_flags: 'Flags / Camouflages',
    wiki_skills: 'Commander Skills',
    wiki_skills_tier: 'Tier',
    wiki_skills_reset: 'Reset Skills',
    wiki_skills_point: 'Point(s)',
    wiki_maps: 'Maps',
    wiki_collections: 'Collections',
    // Extra
    extra_section_title: 'Extra',
    extra_support_wowsinfo: 'Support WoWs Info',
    extra_wowsinfo_re: 'WoWs Info Re',
    extra_wowsinfo_re_subtitle:
      'Try out the new version currently under development',
    extra_rs_beta: 'Realtime Statistics Beta',
    extra_rs_beta_download: 'Download RS on your computer',
    extra_support_wowsinfo_subtitle: 'Donations and Ads',
    support_paypal: 'PayPal',
    support_patreon: 'Patreon',
    support_wechat: 'WeChat',
    // Websites
    website_title: 'Websites',
    website_official_site: 'World of Warships',
    website_premium: 'Premium Shop',
    website_global_wiki: 'Global Wiki',
    website_dev_blog: 'Developer Blog',
    website_sea_group: 'SEA Group',
    website_daily_bounce: 'The Daily Bounce',
    website_numbers: 'WoWS Stats & Numbers',
    website_today: 'Warships.Today',
    website_ranking: 'Player Ranking',
    website_models: 'Warships Models',
    website_game_models: 'GameModels3D',
    website_stats_news_title: 'Statistics & News',
    website_official_title: 'Official Websites',
    website_utility_title: 'Utilities',
    website_ap_calculator: 'Ship AP Calculator',
    website_wowsft: 'WoWs Fitting Tool',
    website_ingame_title: 'In-game Websites',
    website_wargaming_login: 'Wargaming.net Login',
    website_wargaming_login_subtitle:
      'You have to log in first to use websites below. It works better on tablets.',
    website_userbonus: 'My Bonus',
    website_news_ingame: 'In-game News',
    website_ingame_armory: 'My Armory',
    website_ingame_clan: 'My Clan',
    website_ingame_warehouse: 'My Warehouse',
    website_my_logbook: 'My Logbook',
    // CC
    content_creator_title: 'Content Creator',
    content_creator_official: 'WoWs Official',
    content_creator_official_link: 'https://www.youtube.com/user/worldofwarshipscom',
    content_creator_fubuki: 'AozoraFubuki',
    content_creator_fubuki_link: 'https://www.youtube.com/@SYC-HANQ/videos',
    // Tools
    tool_title: 'Tools',
    /// Player section
    // Tabs
    tab_achievement_title: 'Achievement',
    tab_graph_title: 'Graph',
    tab_ship_title: 'Ship',
    tab_rank_title: 'Rank',
    // Rating
    rating_title: 'Personal Rating',
    rating_description: "This rating reflects a player's skill level.",
    rating_read_more: '- Read More -',
    rating_warning:
      'Please refrain from using this rating to judge other players',
    rating_author: 'By Wiochi',
    rating_scale: 'Colour Scale',
    rating_bad: 'Improvement Needed',
    rating_below_average: 'Below Average',
    rating_average: 'Average',
    rating_good: 'Good',
    rating_very_good: 'Very Good',
    rating_great: 'Great',
    rating_unicum: 'Unicum',
    rating_super_unicum: 'SUPER Unicum',
    rating_unknown: 'Unknown',
    // Basic
    basic_data_unknown: 'Unknown',
    basic_level_tier: 'Level',
    basic_register_date: 'Registration Date',
    basic_last_battle: 'Last Battle',
    basic_more_stat: '- Show More -',
    basic_add_friend: 'Add to List',
    basic_set_main: 'Set as Main Account',
    // Detailed
    detailed_win: 'Wins',
    detailed_draw: 'Draws',
    detailed_loss: 'Losses',
    detailed_survived: 'Survived Battles',
    detailed_total_xp: 'Total XP',
    detailed_survived_win: 'Survived Wins',
    detailed_survival_rate: 'Survival Rate',
    detailed_survived_win_rate: 'Survived Win Rate',
    detailed_total_potential_damage: 'Total Potential Damage',
    detailed_avg_potential_damage: 'Avg Potential Damage',
    detailed_total_torp_potential_damage: 'Total Torpedo Potential Damage',
    detailed_avg_torp_potential_damage: 'Avg Torpedo Potential Damage',
    detailed_total_scouting_damage: 'Total Scouting Damage',
    detailed_avg_scouting_damage: 'Avg Scouting Damage',
    detailed_total_damage: 'Total Damage Dealt',
    detailed_damage_potential_ratio: 'Damage Dealt / Potential',
    detailed_total_spotted: 'Total Spotted',
    detailed_avg_spotted: 'Avg Spotted',
    detailed_total_frag: 'Total Frags',
    detailed_frag_spot_ratio: 'Frag / Spotted',
    detailed_total_plane_killed: 'Total Planes Destroyed',
    detailed_avg_plane_killed: 'Avg Planes Destroyed',
    // Ship detail
    ship_detail_damage: 'Damage',
    ship_detail_winrate: 'Winrate',
    ship_detail_frag: 'Frags',
    ship_sort_battle: 'Battle',
    ship_sort_colour: 'Colour',
    // Rank
    rank_season_title: 'Season',
    // Clan
    clan_created_date: 'Creation Date',
    clan_creator_name: 'Creator',
    clan_leader_name: 'Leader',
    clan_member_title: 'Member',
    // Record
    record_title: 'Records',
    record_best_ship: 'Best Ship',
    record_max_damage_dealt: 'Max Damage Dealt',
    record_max_frags_battle: 'Max Frags',
    record_max_planes_killed: 'Max Planes Destroyed',
    record_max_xp: 'Max XP',
    record_max_ships_spotted: 'Max Ships Spotted',
    record_max_total_agro: 'Max Potential Damage Dealt',
    record_max_damage_scouting: 'Max Scouting Damage',
    // Weapon record
    weapon_max_frags: 'Max Frags',
    weapon_total_frags: 'Total Frags',
    weapon_hit_ratio: 'Hit Ratio',
    /// App name section
    app_name: 'WoWs Info Seven',
    wowsinfo_black: 'Black',
    wowsinfo_white: 'White',
    wowsinfo_ultra: 'Ultra',
    wowsinfo_ultimate: 'Ultimate',
    wowsinfo_pro: 'Pro',
    wowsinfo_new: 'New',
    wowsinfo_go: 'Go',
    wowsinfo_origin: 'Origin',
    wowsinfo_free: 'Free',
    /// RS section
    // Tips
    rs_tip_download: '1. Download',
    rs_tip_one:
      'Please visit this GitHub repository and download the latest release. This program does not use a lot of RAM and storage. Currently, it is in its beta stage and has no GUI.\n',
    rs_tip_setup: '2. Setup',
    rs_tip_two:
      "Copy and paste the path of your game folder into this program, and you have to run it with admin or it will not work. It won't do anything harmful to your computer.\n",
    rs_tip_enjoy: '3. Enjoy',
    rs_tip_three:
      'Enter the IP address you see on the screen, and WoWs Info will start giving you real-time statistics for both teams.\n',
    /// Error section
    // General errors
    error_title: 'Error',
    error_download_issue:
      'Failed to update data.\nPlease try again later.\n\nIf the issue persists, please try using a VPN or changing your DNS to "8.8.8.8".\nIf the problem continues, it indicates that the server is unavailable',
    error_timeout: 'Timeout',
    error_pr_corrupted: 'Personal rating data cannot be downloaded',
    /// About WoWs Info section
    // GitHub link
    about_github_link:
      'https://github.com/HenryQuan/WoWs-Info-Origin/blob/master/README.md',
  },
  zh: {
    /// Setup section
    setup_title: '设置 WoWs Info',
    setup_done_button: '完成',
    setup_loading: '加载中...',
    /// Home section
    // Friend section
    friend_clan_title: '工会',
    friend_player_title: '玩家',
    // Update section
    update_version_title: '版本信息',
    update_app_version: 'APP版本 ->',
    update_game_version: '游戏版本 ->',
    // Button section
    button_settings_label: '设置',
    button_menu_label: '主菜单',
    button_back_label: '返回',
    button_home_label: '主页面',
    /// Wiki section
    wiki_warship_footer: '筛选',
    wiki_warship_filter_btn: '确定',
    wiki_warship_reset_btn: '还原',
    wiki_warship_filter_placeholder: '输入船名',
    wiki_warship_filter_tier: '等级',
    wiki_warship_filter_nation: '国家/区域',
    wiki_warship_filter_type: '类型',
    wiki_warship_filter_premium: '金币船',
    // Warship Detail
    warship_unknown: '未知',
    warship_model: '3D模型',
    warship_update_module: '更新组件',
    warship_default_module: '默认组件',
    warship_apply_module: '确定',
    warship_survivability: '生存力',
    warship_survivability_health: '血量',
    warship_survivability_armour: '装甲',
    warship_survivability_protection: '防护',
    warship_artillery: '火炮',
    warship_artillery_main: '主炮',
    warship_avg_damage: '平均伤害',
    warship_avg_winrate: '平均胜率',
    warship_avg_frag: '平均击杀',
    warship_weapon_reload: '装填时间',
    warship_weapon_range: '射程',
    warship_weapon_configuration: '配置',
    warship_weapon_dispersion: '最大散布',
    warship_weapon_rotation: '转动时间',
    warship_weapon_fire_chance: '点火率',
    warship_artillery_main_weight: '重量',
    warship_weapon_damage: '最大伤害',
    warship_weapon_potential_damage: '潜在伤害',
    warship_weapon_ap_overmatch: '碾压',
    warship_weapon_he_penetration: '穿深',
    warship_weapon_speed: '速度',
    warship_ramming: '冲撞',
    warship_artillery_secondary: '副炮',
    warship_torpedoes: '鱼雷',
    warship_torpedoes_visible_distance: '探测距离',
    warship_antiaircraft: '防空',
    warship_maneuverability: '机动性',
    warship_maneuverability_turning: '转舵半径',
    warship_maneuverability_speed: '最大航速',
    warship_maneuverability_rudder_time: '转舵时间',
    warship_aircraft: '飞机',
    warship_concealment: '隐蔽',
    warship_concealment_detect_by_ship: '被船发现距离',
    warship_concealment_detect_by_plane: '被飞机发现距离',
    warship_upgrades: '升级品',
    warship_next_ship: '可升级为',
    warship_compare_similar: '对比类似的战舰',
    /// Menu section
    /// Settings section
    server_name: ['俄服', '欧服', '美服', '亚服'],
    setting_game_server: '游戏服务器',
    setting_api_language: 'API语言',
    setting_api_update_data: '更新服务器数据',
    setting_api_update_data_title: '如果感觉数据没有更新，请使用这个功能',
    setting_api_update_data_update: '更新数据',
    setting_api_update_data_cancel: '取消',
    setting_app_language: 'WoWs Info 语言',
    settings_api_settings: 'API 接口设置',
    settings_app_settings: '软件设置',
    settings_app_dark_mode: '夜间模式',
    settings_app_theme_colour: '主题颜色',
    settings_app_no_image_mode: '无图模式',
    settings_app_swap_buttons: '交换下面的按钮',
    settings_app_send_feedback: '反馈',
    settings_app_send_feedback_subtitle: '给开发者发邮件',
    settings_app_report_issues: '报告错误',
    settings_app_write_review: '给软件打分',
    settings_app_write_review_title: '关于评分和反馈',
    settings_app_write_review_message:
      '如果 APP 有任何问题或者建议，请给开发者发送电子邮件，我们可以一起讨论解决问题。',
    settings_app_write_review_yes: '发送邮件',
    settings_app_write_review_no: '给软件打分',
    settings_app_share: '分享',
    settings_app_share_subtitle: '如果喜欢使用 WoWs Info，记得分享给小伙伴们！',
    settings_app_check_for_update: '检查更新',
    settings_app_no_update: '已经是最新版本',
    settings_app_has_update: '下载 {0} 版本',
    settings_open_source: '开源相关',
    settings_open_source_github: 'Github',
    settings_open_source_licence: '三方许可',
    settings_open_source_licence_subtitle: 'WoWs Info 使用了很多优秀的三方组件',
    // Footer
    menu_footer: '开始搜索',
    menu_search_player: '玩家',
    menu_search_clan: '工会',
    // Pro version
    pro_upgrade_button: '升级到专业版',
    pro_title: 'WoWs Info 专业版',
    pro_rs: '实时数据 Beta 测试版',
    pro_rs_subtitle: '获得每一场战斗的实时数据',
    pro_more_stats: '更多详细数据',
    pro_more_stats_subtitle: '在玩家界面显示更多更详细的数据',
    pro_quick_access_main: '快速查看主账号',
    pro_quick_access_main_subtitle: '一键查看主账号的数据',
    pro_support_development: '支持开发',
    pro_support_development_subtitle: '还有更多功能正在开发中',
    pro_50_off_until_re: '初次购买有5折优惠',
    pro_per_year: '年',
    pro_restore_pro: '恢复购买',
    iap_thx_for_support: '感谢您的支持！',
    iap_no_purchase_history: '您尚未购买专业版',
    iap_pro_expired: 'WoWs Info 专业版已到期',
    // Search bar
    search_player_online: '在线',
    // Wiki
    wiki_section_title: '战舰百科',
    wiki_achievement: '成就',
    wiki_warships: '战舰',
    wiki_upgrades: '升级品',
    wiki_flags: '旗子与迷彩',
    wiki_skills: '舰长技能',
    wiki_skills_tier: '等级',
    wiki_skills_reset: '还原',
    wiki_skills_point: '点',
    wiki_maps: '地图',
    wiki_collections: '收藏',
    // Extra
    extra_section_title: '其他',
    extra_support_wowsinfo: '支持 WoWs Info',
    extra_wowsinfo_re: 'WoWs Info 梦回2016',
    extra_wowsinfo_re_subtitle: '尝试在开发中的全新版本',
    extra_rs_beta: '实时数据 Beta 测试版',
    extra_rs_beta_download: '在电脑上下载 RS',
    extra_support_wowsinfo_subtitle: '捐助以及广告',
    support_paypal: '贝宝',
    support_patreon: 'Patreon',
    support_wechat: '微信',
    // Websites
    website_title: '网站',
    website_official_site: '战舰世界官网',
    website_premium: '战舰商城',
    website_global_wiki: '战舰全球百科',
    website_dev_blog: '开发者的脸书',
    website_sea_group: 'SEA Group',
    website_daily_bounce: 'The Daily Bounce',
    website_numbers: '战舰数字',
    website_today: '今日战舰',
    website_ranking: '玩家排行榜',
    website_models: '战舰模型',
    website_game_models: 'GameModels3D',
    website_stats_news_title: '数据与最新消息',
    website_official_title: '官方网站',
    website_utility_title: '实用工具',
    website_ap_calculator: 'AP 曲线计算器',
    website_wowsft: 'WoWs Fitting Tool',
    website_ingame_title: '游戏内网站',
    website_wargaming_login: '登陆 Wargming.net',
    website_wargaming_login_subtitle:
      '需要登陆才可以使用下面的网站，推荐使用大屏设备',
    website_userbonus: '我的奖赏',
    website_news_ingame: '游戏内新闻',
    website_ingame_armory: '我的武器库',
    website_ingame_clan: '我的工会',
    website_ingame_warehouse: '我的仓库',
    website_my_logbook: '我的航海日志',
    // CC
    content_creator_title: '內容創作者',
    content_creator_official: '战舰世界官方频道',
    content_creator_official_link: 'bilibili://space/573693898',
    content_creator_fubuki: '青空雪舞Channel',
    content_creator_fubuki_link: 'bilibili://space/15653565',
    // Tools
    tool_title: '工具',
    /// Player section
    // Tabs
    tab_achievement_title: '成就',
    tab_graph_title: '图表',
    tab_ship_title: '战舰',
    tab_rank_title: '排位赛',
    // Rating
    rating_title: '个人评分',
    rating_description: '用来测量玩家的技能',
    rating_read_more: '- 阅读更多 -',
    rating_warning: '请不要只用数据来评价玩家',
    rating_author: '舰长 Wiochi',
    rating_scale: '评分表',
    rating_bad: '还需努力',
    rating_below_average: '低于平均',
    rating_average: '平均水平',
    rating_good: '好',
    rating_very_good: '很好',
    rating_great: '非常好',
    rating_unicum: '大佬平均',
    rating_super_unicum: '神佬平均',
    rating_unknown: '水平未知',
    // Basic
    basic_data_unknown: '未知',
    basic_level_tier: '等级',
    basic_register_date: '注册日期',
    basic_last_battle: '最后的战斗',
    basic_more_stat: '- 显示更多数据 -',
    basic_add_friend: '增加到列表',
    basic_set_main: '设为主账号',
    // Detailed
    detailed_win: '胜利',
    detailed_draw: '平局',
    detailed_loss: '失败',
    detailed_survived: '存活场数',
    detailed_total_xp: '总经验',
    detailed_survived_win: '存活胜利',
    detailed_survival_rate: '生存率',
    detailed_survived_win_rate: '存活胜率',
    detailed_total_potential_damage: '总潜在伤害',
    detailed_avg_potential_damage: '平均潜在伤害',
    detailed_total_torp_potential_damage: '鱼雷潜在伤害',
    detailed_avg_torp_potential_damage: '平均鱼雷潜在伤害',
    detailed_total_scouting_damage: '总侦查伤害',
    detailed_avg_scouting_damage: '平均侦查伤害',
    detailed_total_damage: '总伤害',
    detailed_damage_potential_ratio: '真实伤害 / 潜在伤害',
    detailed_total_spotted: '总侦测数',
    detailed_avg_spotted: '平均侦测',
    detailed_total_frag: '总击杀',
    detailed_frag_spot_ratio: '击杀 / 侦测',
    detailed_total_plane_killed: '总飞机击落',
    detailed_avg_plane_killed: '平均飞机击落',
    // Ship detail
    ship_detail_damage: '伤害',
    ship_detail_winrate: '胜率',
    ship_detail_frag: '击杀',
    ship_sort_battle: '场数',
    ship_sort_colour: '颜色',
    // Rank
    rank_season_title: '赛季',
    // Clan
    clan_created_date: '创建于',
    clan_creator_name: '创建者',
    clan_leader_name: '指挥官',
    clan_member_title: '成员',
    // Record
    record_title: '记录',
    record_best_ship: '最好',
    record_max_damage_dealt: '最大伤害',
    record_max_frags_battle: '最多击杀',
    record_max_planes_killed: '最多飞机击落',
    record_max_xp: '最多经验',
    record_max_ships_spotted: '最多侦测',
    record_max_total_agro: '最大潜在伤害',
    record_max_damage_scouting: '最大侦查伤害',
    // Weapon record
    weapon_max_frags: '最多击杀',
    weapon_total_frags: '总击杀',
    weapon_hit_ratio: '命中率',
    /// App name section
    app_name: 'WoWs Info 赛文',
    wowsinfo_black: '黑',
    wowsinfo_white: '白',
    wowsinfo_ultra: '超级版',
    wowsinfo_ultimate: '究极版',
    wowsinfo_pro: '专业版',
    wowsinfo_new: '新',
    wowsinfo_go: 'GO',
    wowsinfo_origin: '起源',
    wowsinfo_free: '自由版',
    /// RS section
    // Tips
    rs_tip_download: '1. 下载',
    rs_tip_one:
      '请访问此 Github 仓库并下载最新版本。此程序不使用大量的 RAM 和存储空间。目前，它处于测试阶段，没有 GUI。\n',
    rs_tip_setup: '2. 设置',
    rs_tip_two:
      '将您游戏文件夹的路径复制并粘贴到此程序中，您必须以管理员身份运行它，否则它将无法工作。它不会对您的计算机造成任何危害。\n',
    rs_tip_enjoy: '3. 使用RS',
    rs_tip_three:
      '输入您在屏幕上看到的 IP 地址，WoWs Info 将开始为您提供双方的实时统计数据。\n',
    /// Error section
    // General errors
    error_title: '错误',
    error_download_issue:
      '无法更新数据，\n请稍后重试。\n\n如果问题依然存在，请尝试修改DNS为【8.8.8.8】或者使用VPN。\n如果还是不可以的话，说明服务器正在维护中。',
    error_timeout: '请求超时',
    error_pr_corrupted: '无法下载评分数据',
    /// About WoWs Info section
    // Github link
    about_github_link:
      'https://github.com/HenryQuan/WoWs-Info-Origin/blob/master/README.md',
  },
  'zh-hant': {
    /// Setup section
    setup_title: '設定 WoWs Info',
    setup_done_button: '完成',
    setup_loading: '載入中...',
    /// Home section
    // Friend section
    friend_clan_title: '公會',
    friend_player_title: '玩家',
    // Update section
    update_version_title: '版本資訊',
    update_app_version: 'APP版本 ->',
    update_game_version: '遊戲版本 ->',
    // Button section
    button_settings_label: '設定',
    button_menu_label: '主選單',
    button_back_label: '返回',
    button_home_label: '主頁面',
    /// Wiki section
    wiki_warship_footer: '篩選',
    wiki_warship_filter_btn: '確定',
    wiki_warship_reset_btn: '還原',
    wiki_warship_filter_placeholder: '輸入艦名',
    wiki_warship_filter_tier: '階級',
    wiki_warship_filter_nation: '國家/地區',
    wiki_warship_filter_type: '類型',
    wiki_warship_filter_premium: '金幣艦',
    // Warship Detail
    warship_unknown: '未知',
    warship_model: '3D模型',
    warship_update_module: '更新模組',
    warship_default_module: '預設模組',
    warship_apply_module: '確定',
    warship_survivability: '生存力',
    warship_survivability_health: '血量',
    warship_survivability_armour: '裝甲',
    warship_survivability_protection: '防護',
    warship_artillery: '火炮',
    warship_artillery_main: '主炮',
    warship_avg_damage: '平均傷害',
    warship_avg_winrate: '平均勝率',
    warship_avg_frag: '平均擊殺',
    warship_weapon_reload: '裝填時間',
    warship_weapon_range: '射程',
    warship_weapon_configuration: '配置',
    warship_weapon_dispersion: '最大散步',
    warship_weapon_rotation: '轉動時間',
    warship_weapon_fire_chance: '點火率',
    warship_artillery_main_weight: '重量',
    warship_weapon_damage: '最大傷害',
    warship_weapon_potential_damage: '潛在傷害',
    warship_weapon_ap_overmatch: '碾壓',
    warship_weapon_he_penetration: '穿深',
    warship_weapon_speed: '速度',
    warship_ramming: '衝撞',
    warship_artillery_secondary: '副炮',
    warship_torpedoes: '魚雷',
    warship_torpedoes_visible_distance: '探測距離',
    warship_antiaircraft: '防空',
    warship_maneuverability: '機動性',
    warship_maneuverability_turning: '轉舵半徑',
    warship_maneuverability_speed: '最大航速',
    warship_maneuverability_rudder_time: '轉舵時間',
    warship_aircraft: '飛機',
    warship_concealment: '隱蔽',
    warship_concealment_detect_by_ship: '被船發現距離',
    warship_concealment_detect_by_plane: '被飛機發現距離',
    warship_upgrades: '升級品',
    warship_next_ship: '可升級為',
    warship_compare_similar: '對比類似的戰艦',
    /// Menu section
    /// Settings section
    server_name: ['俄服', '歐服', '美服', '亞服'],
    setting_game_server: '遊戲伺服器',
    setting_api_language: 'API語言',
    setting_api_update_data: '更新伺服器數據',
    setting_api_update_data_title: '如果感覺數據沒有更新，請使用這個功能',
    setting_api_update_data_update: '更新數據',
    setting_api_update_data_cancel: '取消',
    setting_app_language: 'WoWs Info 語言',
    settings_api_settings: 'API 介面設置',
    settings_app_settings: '軟體設置',
    settings_app_dark_mode: '夜間模式',
    settings_app_theme_colour: '主題顏色',
    settings_app_no_image_mode: '無圖模式',
    settings_app_swap_buttons: '交換下面的按鈕',
    settings_app_send_feedback: '反饋',
    settings_app_send_feedback_subtitle: '給開發者發郵件',
    settings_app_report_issues: '報告錯誤',
    settings_app_write_review: '給軟體打分',
    settings_app_write_review_title: '關於評分和反饋',
    settings_app_write_review_message:
      '如果有任何問題或者建議，請給開發者發送電子郵件，我們可以一起討論解決問題。',
    settings_app_write_review_yes: '發送郵件',
    settings_app_write_review_no: '給軟體打分',
    settings_app_share: '分享',
    settings_app_share_subtitle: '如果喜歡使用 WoWs Info，記得分享給小夥伴們！',
    settings_app_check_for_update: '檢查更新',
    settings_app_no_update: '已經是最新版本',
    settings_app_has_update: '下載 {0} 版本',
    settings_open_source: '開源相關',
    settings_open_source_github: 'Github',
    settings_open_source_licence: '三方許可',
    settings_open_source_licence_subtitle: 'WoWs Info 使用了很多優秀的三方組件',
    // Footer
    menu_footer: '開始搜索',
    menu_search_player: '玩家',
    menu_search_clan: '工會',
    // Pro version
    pro_upgrade_button: '升級到專業版',
    pro_title: 'WoWs Info 專業版',
    pro_rs: '實時數據 Beta 測試版',
    pro_rs_subtitle: '獲得每一場戰鬥的實時數據',
    pro_more_stats: '更多詳細數據',
    pro_more_stats_subtitle: '在玩家界面顯示更多更詳細的數據',
    pro_quick_access_main: '快速查看主帳號',
    pro_quick_access_main_subtitle: '一鍵查看主帳號的數據',
    pro_support_development: '支持開發',
    pro_support_development_subtitle: '還有更多功能正在開發中',
    pro_50_off_until_re: '初次購買有5折優惠',
    pro_per_year: '年',
    pro_restore_pro: '恢復購買',
    iap_thx_for_support: '感謝您的支持！',
    iap_no_purchase_history: '您尚未購買專業版',
    iap_pro_expired: 'WoWs Info 專業版已到期',
    // Search bar
    search_player_online: '在線',
    // Wiki
    wiki_section_title: '戰艦百科',
    wiki_achievement: '成就',
    wiki_warships: '戰艦',
    wiki_upgrades: '升級品',
    wiki_flags: '旗子與迷彩',
    wiki_skills: '艦長技能',
    wiki_skills_tier: '等級',
    wiki_skills_reset: '還原',
    wiki_skills_point: '點',
    wiki_maps: '地圖',
    wiki_collections: '收藏',
    // Extra
    extra_section_title: '其他',
    extra_support_wowsinfo: '支持 WoWs Info',
    extra_wowsinfo_re: 'WoWs Info 夢回2016',
    extra_wowsinfo_re_subtitle: '嘗試在開發中的全新版本',
    extra_rs_beta: '實時數據 Beta 測試版',
    extra_rs_beta_download: '在電腦上下載 RS',
    extra_support_wowsinfo_subtitle: '捐助以及廣告',
    support_paypal: '貝寶',
    support_patreon: 'Patreon',
    support_wechat: '微信',
    // Websites
    website_title: '網站',
    website_official_site: '戰艦世界官網',
    website_premium: '戰艦商城',
    website_global_wiki: '戰艦全球百科',
    website_dev_blog: '開發者的臉書',
    website_sea_group: 'SEA Group',
    website_daily_bounce: 'The Daily Bounce',
    website_numbers: '戰艦數字',
    website_today: '今日戰艦',
    website_ranking: '玩家排行榜',
    website_models: '戰艦模型',
    website_game_models: 'GameModels3D',
    website_stats_news_title: '數據與最新消息',
    website_official_title: '官方網站',
    website_utility_title: '實用工具',
    website_ap_calculator: 'AP 曲線計算器',
    website_wowsft: 'WoWs Fitting Tool',
    website_ingame_title: '遊戲內網站',
    website_wargaming_login: '登陸 Wargming.net',
    website_wargaming_login_subtitle:
      '需要登陸才可以使用下面的網站，推薦使用大屏設備',
    website_userbonus: '我的獎賞',
    website_news_ingame: '遊戲內新聞',
    website_ingame_armory: '我的武器庫',
    website_ingame_clan: '我的工會',
    website_ingame_warehouse: '我的倉庫',
    website_my_logbook: '我的航海日誌',
    // CC
    content_creator_title: '社區貢獻者',
    content_creator_official: '戰艦世界官方頻道',
    content_creator_official_link: 'bilibili://space/573693898',
    content_creator_fubuki: '青空雪舞Channel',
    content_creator_fubuki_link: 'bilibili://space/15653565',
    // Tools
    tool_title: '工具',
    /// Player section
    // Tabs
    tab_achievement_title: '成就',
    tab_graph_title: '圖表',
    tab_ship_title: '戰艦',
    tab_rank_title: '排位賽',
    // Rating
    rating_title: '個人評分',
    rating_description: '用來測量玩家的技能',
    rating_read_more: '- 閱讀更多 -',
    rating_warning: '請不要只用數據來評價玩家',
    rating_author: '艦長 Wiochi',
    rating_scale: '評分表',
    rating_bad: '還需努力',
    rating_below_average: '低於平均',
    rating_average: '平均水平',
    rating_good: '好',
    rating_very_good: '很好',
    rating_great: '非常好',
    rating_unicum: '大佬平均',
    rating_super_unicum: '神佬平均',
    rating_unknown: '水平未知',
    // Basic
    basic_data_unknown: '未知',
    basic_level_tier: '等級',
    basic_register_date: '註冊日期',
    basic_last_battle: '最後的戰鬥',
    basic_more_stat: '- 顯示更多數據 -',
    basic_add_friend: '加為好友',
    basic_set_main: '設為主帳號',
    // Detailed
    detailed_win: '勝利',
    detailed_draw: '平局',
    detailed_loss: '敗北',
    detailed_survived: '存活場數',
    detailed_total_xp: '總經驗',
    detailed_survived_win: '存活勝利',
    detailed_survival_rate: '生存率',
    detailed_survived_win_rate: '存活勝率',
    detailed_total_potential_damage: '總潛在傷害',
    detailed_avg_potential_damage: '平均潛在傷害',
    detailed_total_torp_potential_damage: '魚雷潛在傷害',
    detailed_avg_torp_potential_damage: '平均魚雷潛在傷害',
    detailed_total_scouting_damage: '總偵查傷害',
    detailed_avg_scouting_damage: '平均偵查傷害',
    detailed_total_damage: '總傷害',
    detailed_damage_potential_ratio: '實際傷害 / 潛在傷害',
    detailed_total_spotted: '總偵測數',
    detailed_avg_spotted: '平均偵測',
    detailed_total_frag: '總擊殺',
    detailed_frag_spot_ratio: '擊殺 / 偵測',
    detailed_total_plane_killed: '總擊落飛機數',
    detailed_avg_plane_killed: '平均擊落飛機數',
    // Ship detail
    ship_detail_damage: '傷害',
    ship_detail_winrate: '勝率',
    ship_detail_frag: '擊殺',
    ship_sort_battle: '場數',
    ship_sort_colour: '顏色',
    // Rank
    rank_season_title: '賽季',
    // Clan
    clan_created_date: '創建日期',
    clan_creator_name: '創建者',
    clan_leader_name: '指揮官',
    clan_member_title: '成員',
    // Record
    record_title: '紀錄',
    record_best_ship: '最佳',
    record_max_damage_dealt: '最大傷害',
    record_max_frags_battle: '最多擊殺',
    record_max_planes_killed: '最多飛機擊落',
    record_max_xp: '最多經驗',
    record_max_ships_spotted: '最多偵測',
    record_max_total_agro: '最大潛在傷害',
    record_max_damage_scouting: '最大偵查傷害',
    // Weapon record
    weapon_max_frags: '最多擊殺',
    weapon_total_frags: '總擊殺',
    weapon_hit_ratio: '命中率',
    /// App name section
    app_name: 'WoWs Info 七號',
    wowsinfo_black: '黑',
    wowsinfo_white: '白',
    wowsinfo_ultra: '超級版',
    wowsinfo_ultimate: '究極版',
    wowsinfo_pro: '專業版',
    wowsinfo_new: '新',
    wowsinfo_go: 'GO',
    wowsinfo_origin: '起源',
    wowsinfo_free: '自由版',
    /// RS section
    // Tips
    rs_tip_download: '1. 下載',
    rs_tip_one:
      '請訪問此 Github 倉庫並下載最新版本。此程式不佔用大量 RAM 和儲存空間。目前處於測試階段並無 GUI 介面。\n',
    rs_tip_setup: '2. 設定',
    rs_tip_two:
      '將您的遊戲文件夾路徑複製並貼上至此程式中，然後以管理員身份運行程式，否則將無法運作。此程式不會對您的電腦造成任何損害。\n',
    rs_tip_enjoy: '3. 使用 RS',
    rs_tip_three:
      '輸入您在屏幕上看到的 IP 地址，WoWs Info 將開始為您的兩支隊伍提供即時統計數據。\n',
    /// Error section
    // General errors
    error_title: '錯誤',
    error_download_issue:
      '無法更新數據，\n請稍後重試。\n\n如果問題仍然存在，請嘗試修改 DNS 為【8.8.8.8】或者使用 VPN。\n如果仍然無法解決，可能是服務器正在維護中。',
    error_timeout: '請求超時',
    error_pr_corrupted: '無法下載評分數據',
    /// About WoWs Info section
    // Github link
    about_github_link:
      'https://github.com/HenryQuan/WoWs-Info-Origin/blob/master/README.md',
  },
  ja: {
    /// Setup section
    setup_title: 'WoWs Infoの初期設定',
    setup_done_button: '完了',
    setup_loading: '読み込み中...',
    /// Home section
    // Friend section
    friend_clan_title: 'クラン',
    friend_player_title: 'プレーヤー',
    // Update section
    update_version_title: 'バージョン',
    update_app_version: 'アプリ ->',
    update_game_version: 'ゲーム ->',
    // Button section
    button_settings_label: '設定',
    button_menu_label: 'メニュー',
    button_back_label: '戻る',
    button_home_label: 'ホーム',
    /// Wiki section
    wiki_warship_footer: 'フィルター',
    wiki_warship_filter_btn: '適用',
    wiki_warship_reset_btn: 'リセット',
    wiki_warship_filter_placeholder: '名前を入力',
    wiki_warship_filter_tier: 'ティア',
    wiki_warship_filter_nation: '国／地区',
    wiki_warship_filter_type: '艦種',
    wiki_warship_filter_premium: 'プレミアム艦',
    // Warship Detail
    warship_unknown: '不明',
    warship_model: '3Dモデル',
    warship_update_module: 'モジュール変更',
    warship_default_module: '初期モジュール',
    warship_apply_module: '適用',
    warship_survivability: '生存力',
    warship_survivability_health: 'HP',
    warship_survivability_armour: '装甲',
    warship_survivability_protection: '対水雷防御',
    warship_artillery: '火砲',
    warship_artillery_main: '主砲',
    warship_avg_damage: '平均ダメージ',
    warship_avg_winrate: '勝率',
    warship_avg_frag: '艦船撃沈',
    warship_weapon_reload: '装填時間',
    warship_weapon_range: '射程',
    warship_weapon_configuration: '配置',
    warship_weapon_dispersion: '最大散布',
    warship_weapon_rotation: '旋回時間',
    warship_weapon_fire_chance: '火災発生率',
    warship_artillery_main_weight: '重量',
    warship_weapon_damage: '最大ダメージ',
    warship_weapon_potential_damage: '潜在ダメージ',
    warship_weapon_ap_overmatch: 'オーバーマッチ',
    warship_weapon_he_penetration: '装甲貫通力',
    warship_weapon_speed: '速度',
    warship_ramming: '体当たり',
    warship_artillery_secondary: '副砲',
    warship_torpedoes: '魚雷',
    warship_torpedoes_visible_distance: '探知距離',
    warship_antiaircraft: '対空火力',
    warship_maneuverability: '機動性',
    warship_maneuverability_turning: '旋回半径',
    warship_maneuverability_speed: '最大速度',
    warship_maneuverability_rudder_time: '転舵時間',
    warship_aircraft: '航空機',
    warship_concealment: '隠蔽性',
    warship_concealment_detect_by_ship: '海上探知距離',
    warship_concealment_detect_by_plane: '航空探知距離',
    warship_upgrades: 'アップグレード',
    warship_next_ship: '次の艦',
    warship_compare_similar: '類似艦の比較',
    /// Menu section
    /// Settings section
    server_name: ['ロシア', 'ヨーロッパ', '北アメリカ', 'アジア'],
    setting_game_server: 'ゲームサーバー',
    setting_api_language: 'API言語',
    setting_api_update_data: 'データ更新',
    setting_api_update_data_title: 'データがない場合に使用',
    setting_api_update_data_update: '更新',
    setting_api_update_data_cancel: 'キャンセル',
    setting_app_language: 'WoWs Info言語',
    settings_api_settings: 'API設定',
    settings_app_settings: 'アプリ設定',
    settings_app_dark_mode: 'ダークモード',
    settings_app_theme_colour: 'テーマ色',
    settings_app_no_image_mode: '省データモード',
    settings_app_swap_buttons: 'ボタン入れ替え',
    settings_app_send_feedback: 'フィードバック',
    settings_app_send_feedback_subtitle: '開発者にメール',
    settings_app_report_issues: '問題報告',
    settings_app_write_review: 'レビューを書く',
    settings_app_write_review_title: 'レビューとフィードバック',
    settings_app_write_review_message:
      'アプリに関する質問、問題、提案は開発者にご連絡ください。',
    settings_app_write_review_yes: '開発者にメール',
    settings_app_write_review_no: 'レビューを書く',
    settings_app_share: 'シェア',
    settings_app_share_subtitle: '友達にシェア',
    settings_app_check_for_update: 'アップデートを確認',
    settings_app_no_update: '最新バージョンです',
    settings_app_has_update: 'アップデートあり {0}',
    settings_open_source: 'オープンソース',
    settings_open_source_github: 'Github',
    settings_open_source_licence: 'ライセンス',
    settings_open_source_licence_subtitle: '本アプリに使用したモジュール',
    // Footer
    menu_footer: '検索',
    menu_search_player: 'プレーヤー',
    menu_search_clan: 'クラン',
    // Pro version
    pro_upgrade_button: 'プロバージョンにアップグレード',
    pro_title: 'WoWs Info プロ',
    pro_rs: 'リアルタイム統計 Beta',
    pro_rs_subtitle: 'リアルタイムで戦闘情報を表示',
    pro_more_stats: '詳細情報',
    pro_more_stats_subtitle: 'プレーヤー情報の詳細表示',
    pro_quick_access_main: 'メインプレーヤー',
    pro_quick_access_main_subtitle: 'ホームページでアカウントにアクセス',
    pro_support_development: '開発支援',
    pro_support_development_subtitle: '新機能の開発サポート',
    pro_50_off_until_re: '初回購入 50% OFF！',
    pro_per_year: '年間',
    pro_restore_pro: '購入済みの場合、ここをタップ',
    iap_thx_for_support: 'ご支援ありがとうございます！',
    iap_no_purchase_history: '支払い履歴がありません',
    iap_pro_expired: 'プロバージョンの有効期限が切れました',
    // Search bar
    search_player_online: 'オンライン',
    // Wiki
    wiki_section_title: '百科事典',
    wiki_achievement: '実績',
    wiki_warships: '艦艇',
    wiki_upgrades: 'アップグレード',
    wiki_flags: '信号旗',
    wiki_skills: '艦長スキル',
    wiki_skills_tier: 'ティア',
    wiki_skills_reset: 'リセット',
    wiki_skills_point: 'ポイント',
    wiki_maps: '地図',
    wiki_collections: 'コレクション',
    // Extra
    extra_section_title: 'その他',
    extra_support_wowsinfo: 'WoWs Info支援',
    extra_wowsinfo_re_subtitle: '開発中の新バージョン',
    extra_wowsinfo_re: 'WoWs Info 2016年の夢',
    extra_rs_beta: 'リアルタイム統計 Beta',
    extra_rs_beta_download: 'パソコンでダウンロード',
    extra_support_wowsinfo_subtitle: '寄付と広告',
    support_paypal: 'ペイパル',
    support_patreon: 'パトレオン',
    support_wechat: 'WeChat',
    // Websites
    website_title: 'ウェブサイト',
    website_official_site: 'World of Warships',
    website_premium: 'プレミアムショップ',
    website_global_wiki: 'グローバルウィキ',
    website_dev_blog: '開発者ブログ',
    website_sea_group: 'シーグループ',
    website_daily_bounce: 'デイリーバウンス',
    website_numbers: 'WoWS Stats & Numbers',
    website_today: 'Warships.Today',
    website_ranking: 'プレーヤーランキング',
    website_models: '艦艇モデル',
    website_game_models: 'GameModels3D',
    website_stats_news_title: '統計と情報',
    website_official_title: '公式サイト',
    website_utility_title: 'ツール',
    website_ap_calculator: 'APダメージ計算機',
    website_wowsft: 'WoWs Fitting Tool',
    website_ingame_title: 'ゲーム内サイト',
    website_wargaming_login: 'Wargaming.net ログイン',
    website_wargaming_login_subtitle: 'ログインして使う',
    website_userbonus: '私のボーナス',
    website_news_ingame: 'ゲーム内ニュース',
    website_ingame_armory: '私の武器庫',
    website_ingame_clan: '私のクラン',
    website_ingame_warehouse: '私の倉庫',
    website_my_logbook: '私の航海記録',
    // content_creators
    content_creator_title: 'コンテンツクリエイター',
    content_creator_official: 'WoWs公式チャンネル',
    content_creator_official_link: 'https://www.youtube.com/user/worldofwarshipscom',
    content_creator_fubuki: '青空雪舞Channel',
    content_creator_fubuki_link: 'bilibili://space/15653565',
    // Tools
    tool_title: 'ツール',
    /// Player section
    // Tabs
    tab_achievement_title: '実績',
    tab_graph_title: 'グラフ',
    tab_ship_title: '艦',
    tab_rank_title: 'ランク',
    // Rating
    rating_title: '操艦評価',
    rating_description: 'プレイヤーレベルの評価方法',
    rating_read_more: '- 詳細情報 -',
    rating_warning: '評価で人を判断しないでください',
    rating_author: 'Wiochi艦長による',
    rating_scale: '評価スケール',
    rating_bad: '改善の余地あり',
    rating_below_average: '平均以下',
    rating_average: '平均',
    rating_good: '良好',
    rating_very_good: 'とても良好',
    rating_great: '素晴らしい',
    rating_unicum: 'ユニカム',
    rating_super_unicum: 'スーパーユニカム',
    rating_unknown: '不明',
    // Basic
    basic_data_unknown: '不明',
    basic_level_tier: 'レベル',
    basic_register_date: '登録日',
    basic_last_battle: '最後の戦闘',
    basic_more_stat: '- 詳細情報 -',
    basic_add_friend: 'フレンド追加',
    basic_set_main: 'メインプレーヤーに設定',
    // Detailed
    detailed_win: '勝利',
    detailed_draw: '引き分け',
    detailed_loss: '敗北',
    detailed_survived: '生存',
    detailed_total_xp: '総XP',
    detailed_survived_win: '生存勝利',
    detailed_survival_rate: '生存率',
    detailed_survived_win_rate: '生存勝率',
    detailed_total_potential_damage: '総潜在ダメージ',
    detailed_avg_potential_damage: '平均潜在ダメージ',
    detailed_total_torp_potential_damage: '総水雷潜在ダメージ',
    detailed_avg_torp_potential_damage: '平均水雷潜在ダメージ',
    detailed_total_scouting_damage: '総探知ダメージ',
    detailed_avg_scouting_damage: '平均探知ダメージ',
    detailed_total_damage: '総与ダメージ',
    detailed_damage_potential_ratio: '与ダメージ / 潜在ダメージ',
    detailed_total_spotted: '総探知数',
    detailed_avg_spotted: '平均探知数',
    detailed_total_frag: '総撃沈数',
    detailed_frag_spot_ratio: '撃沈数 / 探知数',
    detailed_total_plane_killed: '総撃墜数',
    detailed_avg_plane_killed: '平均撃墜数',
    // Ship detail
    ship_detail_damage: '与ダメージ',
    ship_detail_winrate: '勝率',
    ship_detail_frag: '撃沈数',
    ship_sort_battle: '戦闘数',
    ship_sort_colour: 'カラー',
    // Rank
    rank_season_title: 'シーズン',
    // Clan
    clan_created_date: '設立日',
    clan_creator_name: '設立者',
    clan_leader_name: 'クランマスター',
    clan_member_title: 'メンバー',
    // Record
    record_title: '最高記録',
    record_best_ship: '最良の艦',
    record_max_damage_dealt: '最大与ダメージ',
    record_max_frags_battle: '最大撃沈数',
    record_max_planes_killed: '最大撃墜数',
    record_max_xp: '最大XP',
    record_max_ships_spotted: '最大探知数',
    record_max_total_agro: '最大潜在ダメージ',
    record_max_damage_scouting: '最大探知ダメージ',
    // Weapon record
    weapon_max_frags: '最大撃沈数',
    weapon_total_frags: '総撃沈数',
    weapon_hit_ratio: '命中率',
    /// App name section
    app_name: 'WoWs Info セブン',
    wowsinfo_black: '黒',
    wowsinfo_white: '白',
    wowsinfo_ultra: 'ウルトラ',
    wowsinfo_ultimate: 'アルティメット',
    wowsinfo_pro: 'プロ',
    wowsinfo_new: 'ニュー',
    wowsinfo_go: 'ゴー',
    wowsinfo_origin: 'オリジン',
    wowsinfo_free: 'フリー',
    /// RS section
    // Tips
    rs_tip_download: '1. ダウンロード',
    rs_tip_one:
      'このGitHubリポジトリを訪問し、最新リリースをダウンロードしてください。 このプログラムは多くのRAMとストレージを使用しません。 現在、ベータステージにあり、GUIはありません。\n',
    rs_tip_setup: '2. セットアップ',
    rs_tip_two:
      'ゲームフォルダーのパスをこのプログラムにコピーして貼り付け、管理者として実行する必要があります。 そうしないと動作しません。 あなたのコンピューターに有害なことはありません。\n',
    rs_tip_enjoy: '3. 楽しむ',
    rs_tip_three:
      '画面に表示されるIPアドレスを入力すると、WoWs Infoが両チームのリアルタイムの統計情報を提供し始めます。\n',
    /// Error section
    // General errors
    error_title: 'エラー',
    error_download_issue:
      'アップデートのダウンロードに失敗しました。\n再試行してください。\n\n繰り返し失敗する場合は、VPNを使用したり、DNSを「8.8.8.8」に変更したりしてみてください。 メンテナンス中の可能性もあります。',
    error_timeout: 'タイムアウト',
    error_pr_corrupted: 'プレイヤーレートのデータがダウンロードできません',
    /// About WoWs Info section
    // Github link
    about_github_link:
      'https://github.com/HenryQuan/WoWs-Info-Origin/blob/master/README.md',
  },
});
