# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#
actions_path "../../../fastlane/fastlane/actions"

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  private_lane :bundle_react_native do
    # The bundle is a reference in Xcode, it needs to be build before archiving
    sh "cd ../.. && npx react-native bundle --dev false --entry-file index.js --bundle-output ios/main.jsbundle --platform ios"
  end

  desc "Building the app for release"
  lane :beta do
    ios_testflight(
      ipa_path: "../wowsinfo.ipa",
      display_name: "WoWs Info",
    )
  end

  desc "Building the app for testing on simulators"
  lane :build_simulator do
    bundle_react_native
    build_any_simulator(
      scheme: "wowsinfo",
      workspace: "wowsinfo.xcworkspace",
      output_directory: "build/",
    )
  end

  # required by the fastlane module
  private_lane :build do |options|
    # cd inside the fastlane folder
    Dir.chdir("fastlane")

    bundle_react_native
    # gym exports to testflight directly once the app is built
    gym(
      scheme: "wowsinfo",
      configuration: "Release",
      export_method: "app-store",
      # use the correct provisioning profile
      export_options: {
        provisioningProfiles: {
          "com.yihengquan.WoWs-Info": "match AppStore com.yihengquan.WoWs-Info",
        },
      },
    )
  end
end
