# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command("node", ["-p",
                                                 'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

$IOS_TARGET = "14.0"
platform :ios, $IOS_TARGET
prepare_react_native_project!

# https://stackoverflow.com/a/78265475
# See https://github.com/facebook/react-native/issues/43335
# Upgrade React Native later and see if this is still needed.
$rn_config = use_native_modules!

linkage = ENV["USE_FRAMEWORKS"]
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

def setup_common_pods
  use_react_native!(
    :path => $rn_config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
  )
end

target "wowsinfo" do
  setup_common_pods
end

target "wowsinfo-debug" do
  setup_common_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = $IOS_TARGET
      # https://github.com/facebook/react-native/issues/36763#issuecomment-1512798923
      # clang warns when we use the RCT_EXTERN_MODULE
      config.build_settings["CLANG_WARN_STRICT_PROTOTYPES"] = "NO"
    end
  end

  # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
  react_native_post_install(
    installer,
    $rn_config[:reactNativePath],
    :mac_catalyst_enabled => false,
    # :ccache_enabled => true
  )
end
